services:
    notebooks:
        image: pc-example-notebooks
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8888:8888"
        volumes:
            - ./datasets:/opt/src/datasets
            - ./quickstarts:/opt/src/quickstarts
            - ./tutorials:/opt/src/tutorials
    localserver:
        image: python:3.9-alpine
        ports:
            - "8889:8889"
        volumes:
            - ./datasets:/opt/src/datasets
            - ./quickstarts:/opt/src/quickstarts
            - ./tutorials:/opt/src/tutorials
        command: python3 -m "http.server" 8889 -d /opt/src